### ISSUE TITLE
removing resistance from banneed skills

### ISSUE THREAD

**Issue by saneok15** [temig74/HotaTreeCalc#1]
removing resistance from banned skills causes wrong tree calculations

**Comment by temig74** [comment]
Please write what hero you calculated, and number of tree, so i could check it.
In my tests on a template with resistance allowed, when i deleted resistance from banned skills in program, calculations were correct.
You can try new version 1.04

**Comment by saneok15** [comment]
i presume if no skills are banned all trees are calculated wrong all the times. A simple example on 6lm10a. In teaplate settings are not any forbidden skills, but hota excludes navigation if map has no water. Gundula is a battle mage. On 2 lvl up i got +sp and advanced wisdom or basic resistance. Program shows no tree number. From what i tested (with default banned resistance and navigation and removing  one or both from banned) trees are correct only when in banned skills are resistance and navigation. But considering resistance isnt banned on map and you can get it sometimes that means branches with resistance are prunned or smth else.

**Comment by temig74** [comment]
I checked using my program and using LMoracle, there are only 3 trees when Gundula gets widsom and resistance on 2 level on a map with only navigation banned and resistance allowed:
tree 43: knowledgde wisdom resistance
tree 101: attack wisdom resistance
tree 217: attack wisdom resistance

so primary is attack or knowledge, not SP in these cases.

You really get +sp widsom resistance on 2 level for Gundula on a map in Hota without water, where resistance is allowed in template settings?

According to programs, this option is possible in Sod, where interference banned, and resistance and navigation are allowed:
trees №59 and 65

By default, resistance and navigation are banned on templates without water in Hota, and interference allowed instead of resistance.
Maybe you mixed up resistance and interference?

There is a tree №65 when she gets SP, wisdom and interference on 2 level.

**Comment by saneok15** [comment]
you are right, I mixed up resistance and interference, sorry for taking up your time
